spring.application.name=app-booking

spring.datasource.url=jdbc:sqlite:hotel.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
# spring.sql.init.mode=never
spring.sql.init.mode=always

secretJwtString= kevin123456789kevin123456789kevin123456789

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kr.salazar98@gmail.com
spring.mail.password=Kevintest
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true